version: '3'
services:
  mysql-master:
    image: mysql:8.0
    container_name: master_1
    restart: always
    env_file:
      - C:\Users\Danil\sdb-hw\Replication_&_scale\.env
    cap_add:
      - all
    volumes:
      - C:\Users\Danil\sdb-hw\Replication_&_scale\master-master\master_1\my.cnf:/etc/my.cnf:ro
    environment:
      - TZ=${TZ}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    networks:
      default:
        aliases:
          - mysql

  mysql-slave:
    image: mysql:8.0
    container_name: master_2
    restart: always
    env_file:
      - C:\Users\Danil\sdb-hw\Replication_&_scale\.env
    cap_add:
      - all
    volumes:
      - C:\Users\Danil\sdb-hw\Replication_&_scale\master-master\master_2\my.cnf:/etc/my.cnf:ro
    environment:
      - TZ=${TZ}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    networks:
      default:
        aliases:
          - mysql