version: '3'
services:
  mysql-master:
    image: mysql:8.0
    container_name: master
    restart: always
    env_file:
      - .env
    cap_add:
      - all
    volumes:
      - ./master/my.cnf:/etc/my.cnf:ro
    environment:
      - TZ=${TZ}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    networks:
      default:
        aliases:
          - mysql

  mysql-slave:
    image: mysql:8.0
    container_name: slave
    restart: always
    env_file:
      - .env
    cap_add:
      - all
    volumes:
      - ./slave/my.cnf:/etc/my.cnf:ro
    environment:
      - TZ=${TZ}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    networks:
      default:
        aliases:
          - mysql